# Generated by Django 5.0.2 on 2024-03-11 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_todo_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="done",
        ),
    ]
